# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_merge'),
        ('profiles', '0005_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(to='place.Place'),
        ),
    ]
