# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.1 on 2016-01-20 16:37
=======
# Generated by Django 1.9.1 on 2016-01-23 13:19
>>>>>>> f8389f28cdae36e0ae6aa5c4120d45138ed265b7
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_auto_20160120_2035'),
        ('place', '0007_auto_20160120_2020'),
    ]

    operations = [
    ]
